[phases.setup]
nixPkgs = ["php82", "nodejs", "git"]

[phases.build]
cmds = ["composer install --no-interaction --optimize-autoloader --no-dev", "npm install", "npm run build"]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
